### ISSUE TITLE
Filtering order notes

### ISSUE THREAD

**Issue by josegrad** [woocommerce/wc-api-ruby#28]
Should the filter for order notes be possible?
I would like to get the order notes that are only private or public.

````
shop_client.get "orders/112/notes", :customer_note => true
shop_client.get "orders/112/notes",{'filter' => {'customer_note' => true}}
shop_client.get "orders/112/notes?filter[customer_note]=true"
````

All of those always return all the notes for the order, regardless of the customer_note value.
Or then my queries are wrong.

**Comment by claudiosmweb** [comment]
Not an issue with this wrapper.
Need to add support to filter notes in the new WooCommerce REST API.
