### ISSUE TITLE
Update an order line_items meta

### ISSUE THREAD

**Issue by josegrad** [woocommerce/wc-api-ruby#30]
Is there a way to update or add new meta to line_items in an order?

shop_client.put("orders/117", {:line_items => [{"product_id" => 73, "meta" => {"key" => "serial_number", "label" => "SN", "value" => "23423234"}, "quantity" => 1}]})

This does now give any errors but the meta is not affected...

**Comment by claudiosmweb** [comment]
Don't looks like a question about this library.
You should check the REST API docs: https://woocommerce.github.io/woocommerce-rest-api-docs/
And if you have questions about the WooCommerce REST API you should use the plugin forum: https://wordpress.org/support/plugin/woocommerce
