### ISSUE TITLE
JSON Parse error

### ISSUE THREAD

**Issue by ayalaalex** [woocommerce/wc-api-ruby#37]
I'm getting error when issuing a get product
p = woocommerce.get("products", sku: barcode)

logs:

<b>Notice</b>:  Use of undefined constant WP_CACHE_KEY_SALT - assumed 'WP_CACHE_
KEY_SALT' in <b>/home/content/p3pnexwpnas16_data03/70/3665770/html/wp-content/ob
ject-cache.php</b> on line <b>1294</b><br />
<br />
<b>Notice</b>:  Use of undefined constant WP_CACHE_KEY_SALT - assumed 'WP_CACHE_
KEY_SALT' in <b>/home/content/p3pnexwpnas16_data03/70/3665770/html/wp-content/ob
ject-cache.php</b> on line <b>1294</b><br />
<br />
<b>Notice</b>:  Use of undefined constant WP_CACHE_KEY_SALT - assumed 'WP_CACHE_
KEY_SALT' in <b>/home/content/p3pnexwpnas16_data03/70/3665770/html/wp-content/ob
ject-cache.php</b> on line <b>1294</b><br />
<br />
<b>Notice</b>:  Use of undefined constant WP_CACHE_KEY_SALT - assumed 'WP_CACHE_
KEY_SALT' in <b>/home/content/p3pnexwpnas16_data03/70/3665770/html/wp-content/ob
ject-cache.php</b> on line <b>1294</b><br />
<br />
<b>Notice</b>:  Use of undefined constant WP_CACHE_KEY_SALT - assumed 'WP_CACHE_
KEY_SALT' in <b>/home/content/p3pnexwpnas16_data03/70/3665770/html/wp-content/ob
ject-cache.php</b> on line <b>1294</b><br />
<br />
<b>Notice</b>:  Use of undefined constant WP_CACHE_KEY_SALT - assumed 'WP_CACHE_
KEY_SALT' in <b>/home/content/p3pnexwpnas16_data03/70/3665770/html/wp-content/ob
ject-cache.php</b> on line <b>1294</b><br />
<br />
<b>Notice</b>:  Use of undefined constant WP_CACHE_KEY_SALT - assumed 'WP_CACHE_
KEY_SALT' in <b>/home/content/p3pnexwpnas16_data03/70/3665770/html/wp-content/ob
ject-cache.php</b> on line <b>1294</b><br />
<br />
<b>Notice</b>:  Use of undefined constant WP_CACHE_KEY_SALT - assumed 'WP_CACHE_
KEY_SALT' in <b>/home/content/p3pnexwpnas16_data03/70/3665770/html/wp-content/ob
ject-cache.php</b> on line <b>1294</b><br />
<br />
<b>Notice</b>:  Use of undefined constant WP_CACHE_KEY_SALT - assumed 'WP_CACHE_
KEY_SALT' in <b>/home/content/p3pnexwpnas16_data03/70/3665770/html/wp-content/ob
ject-cache.php</b> on line <b>1294</b><br />
<br />
<b>Notice</b>:  Use of undefined constant WP_CACHE_KEY_SALT - assumed 'WP_CACHE_
KEY_SALT' in <b>/home/content/p3pnexwpnas16_data03/70/3665770/html/wp-content/ob
ject-cache.php</b> on line <b>1294</b><br />
<br />
<b>Notice</b>:  Use of undefined constant WP_CACHE_KEY_SALT - assumed 'WP_CACHE_
KEY_SALT' in <b>/home/content/p3pnexwpnas16_data03/70/3665770/html/wp-content/ob
ject-cache.php</b> on line <b>1294</b><br />
<br />
<b>Notice</b>:  Use of undefined constant WP_CACHE_KEY_SALT - assumed 'WP_CACHE_
KEY_SALT' in <b>/home/content/p3pnexwpnas16_data03/70/3665770/html/wp-content/ob
ject-cache.php</b> on line <b>1294</b><br />
<br />
<b>Notice</b>:  Use of undefined constant WP_CACHE_KEY_SALT - assumed 'WP_CACHE_
KEY_SALT' in <b>/home/content/p3pnexwpnas16_data03/70/3665770/html/wp-content/ob
ject-cache.php</b> on line <b>1294</b><br />
<br />
<b>Notice</b>:  Use of undefined constant WP_CACHE_KEY_SALT - assumed 'WP_CACHE_
KEY_SALT' in <b>/home/content/p3pnexwpnas16_data03/70/3665770/html/wp-content/ob
ject-cache.php</b> on line <b>1294</b><br />
<br />
<b>Notice</b>:  Use of undefined constant WP_CACHE_KEY_SALT - assumed 'WP_CACHE_
KEY_SALT' in <b>/home/content/p3pnexwpnas16_data03/70/3665770/html/wp-content/ob
ject-cache.php</b> on line <b>1294</b><br />
<br />
<b>Notice</b>:  Use of undefined constant WP_CACHE_KEY_SALT - assumed 'WP_CACHE_
KEY_SALT' in <b>/home/content/p3pnexwpnas16_data03/70/3665770/html/wp-content/ob
ject-cache.php</b> on line <b>1294</b><br />
<br />
<b>Notice</b>:  Use of undefined constant WP_CACHE_KEY_SALT - assumed 'WP_CACHE_
KEY_SALT' in <b>/home/content/p3pnexwpnas16_data03/70/3665770/html/wp-content/ob
ject-cache.php</b> on line <b>1294</b><br />
<br />
<b>Notice</b>:  Use of undefined constant WP_CACHE_KEY_SALT - assumed 'WP_CACHE_
KEY_SALT' in <b>/home/content/p3pnexwpnas16_data03/70/3665770/html/wp-content/ob
ject-cache.php</b> on line <b>1294</b><br />
<br />
<b>Notice</b>:  Use of undefined constant WP_CACHE_KEY_SALT - assumed 'WP_CACHE_
KEY_SALT' in <b>/home/content/p3pnexwpnas16_data03/70/3665770/html/wp-content/ob
ject-cache.php</b> on line <b>1294</b><br />
<br />
<b>Notice</b>:  Use of undefined constant WP_CACHE_KEY_SALT - assumed 'WP_CACHE_
KEY_SALT' in <b>/home/content/p3pnexwpnas16_data03/70/3665770/html/wp-content/ob
ject-cache.php</b> on line <b>1294</b><br />
<br />
<b>Notice</b>:  Use of undefined constant WP_CACHE_KEY_SALT - assumed 'WP_CACHE_
KEY_SALT' in <b>/home/content/p3pnexwpnas16_data03/70/3665770/html/wp-content/ob
ject-cache.php</b> on line <b>1294</b><br />
<br />
<b>Notice</b>:  Use of undefined constant WP_CACHE_KEY_SALT - assumed 'WP_CACHE_
KEY_SALT' in <b>/home/content/p3pnexwpnas16_data03/70/3665770/html/wp-content/ob
ject-cache.php</b> on line <b>1294</b><br />
<br />
<b>Notice</b>:  Use of undefined constant WP_CACHE_KEY_SALT - assumed 'WP_CACHE_
KEY_SALT' in <b>/home/content/p3pnexwpnas16_data03/70/3665770/html/wp-content/ob
ject-cache.php</b> on line <b>1294</b><br />
<br />
<b>Notice</b>:  Use of undefined constant WP_CACHE_KEY_SALT - assumed 'WP_CACHE_
KEY_SALT' in <b>/home/content/p3pnexwpnas16_data03/70/3665770/html/wp-content/ob
ject-cache.php</b> on line <b>1294</b><br />
<br />
<b>Notice</b>:  Use of undefined constant WP_CACHE_KEY_SALT - assumed 'WP_CACHE_
KEY_SALT' in <b>/home/content/p3pnexwpnas16_data03/70/3665770/html/wp-content/ob
ject-cache.php</b> on line <b>1294</b><br />
<br />
<b>Notice</b>:  Use of undefined constant WP_CACHE_KEY_SALT - assumed 'WP_CACHE_
KEY_SALT' in <b>/home/content/p3pnexwpnas16_data03/70/3665770/html/wp-content/ob
ject-cache.php</b> on line <b>1294</b><br />
<br />
<b>Notice</b>:  Use of undefined constant WP_CACHE_KEY_SALT - assumed 'WP_CACHE_
KEY_SALT' in <b>/home/content/p3pnexwpnas16_data03/70/3665770/html/wp-content/ob
ject-cache.php</b> on line <b>1294</b><br />
<br />
<b>Notice</b>:  Use of undefined constant WP_CACHE_KEY_SALT - assumed 'WP_CACHE_
KEY_SALT' in <b>/home/content/p3pnexwpnas16_data03/70/3665770/html/wp-content/ob
ject-cache.php</b> on line <b>1294</b><br />
<br />
<b>Notice</b>:  Use of undefined constant WP_CACHE_KEY_SALT - assumed 'WP_CACHE_
KEY_SALT' in <b>/home/content/p3pnexwpnas16_data03/70/3665770/html/wp-content/ob
ject-cache.php</b> on line <b>1294</b><br />
<br />
<b>Notice</b>:  Use of undefined constant WP_CACHE_KEY_SALT - assumed 'WP_CACHE_
KEY_SALT' in <b>/home/content/p3pnexwpnas16_data03/70/3665770/html/wp-content/ob
ject-cache.php</b> on line <b>1294</b><br />
<br />
<b>Notice</b>:  Use of undefined constant WP_CACHE_KEY_SALT - assumed 'WP_CACHE_
KEY_SALT' in <b>/home/content/p3pnexwpnas16_data03/70/3665770/html/wp-content/ob
ject-cache.php</b> on line <b>1294</b><br />
<br />
<b>Notice</b>:  Use of undefined constant WP_CACHE_KEY_SALT - assumed 'WP_CACHE_
KEY_SALT' in <b>/home/content/p3pnexwpnas16_data03/70/3665770/html/wp-content/ob
ject-cache.php</b> on line <b>1294</b><br />
<br />
<b>Notice</b>:  Use of undefined constant WP_CACHE_KEY_SALT - assumed 'WP_CACHE_
KEY_SALT' in <b>/home/content/p3pnexwpnas16_data03/70/3665770/html/wp-content/ob
ject-cache.php</b> on line <b>1294</b><br />
<br />
<b>Notice</b>:  Use of undefined constant WP_CACHE_KEY_SALT - assumed 'WP_CACHE_
KEY_SALT' in <b>/home/content/p3pnexwpnas16_data03/70/3665770/html/wp-content/ob
ject-cache.php</b> on line <b>1294</b><br />
<br />
<b>Notice</b>:  Use of undefined constant WP_CACHE_KEY_SALT - assumed 'WP_CACHE_
KEY_SALT' in <b>/home/content/p3pnexwpnas16_data03/70/3665770/html/wp-content/ob
ject-cache.php</b> on line <b>1294</b><br />
<br />
<b>Notice</b>:  Use of undefined constant WP_CACHE_KEY_SALT - assumed 'WP_CACHE_
KEY_SALT' in <b>/home/content/p3pnexwpnas16_data03/70/3665770/html/wp-content/ob
ject-cache.php</b> on line <b>1294</b><br />
<br />
<b>Notice</b>:  Use of undefined constant WP_CACHE_KEY_SALT - assumed 'WP_CACHE_
KEY_SALT' in <b>/home/content/p3pnexwpnas16_data03/70/3665770/html/wp-content/ob
ject-cache.php</b> on line <b>1294</b><br />
<br />
<b>Notice</b>:  Use of undefined constant WP_CACHE_KEY_SALT - assumed 'WP_CACHE_
KEY_SALT' in <b>/home/content/p3pnexwpnas16_data03/70/3665770/html/wp-content/ob
ject-cache.php</b> on line <b>1294</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (out
put started at /home/content/p3pnexwpnas16_data03/70/3665770/html/wp-content/obj
ect-cache.php:1294) in <b>/home/content/p3pnexwpnas16_data03/70/3665770/html/wp-
includes/rest-api/class-wp-rest-server.php</b> on line <b>1244</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (out
put started at /home/content/p3pnexwpnas16_data03/70/3665770/html/wp-content/obj
ect-cache.php:1294) in <b>/home/content/p3pnexwpnas16_data03/70/3665770/html/wp-
includes/rest-api/class-wp-rest-server.php</b> on line <b>1244</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (out
put started at /home/content/p3pnexwpnas16_data03/70/3665770/html/wp-content/obj
ect-cache.php:1294) in <b>/home/content/p3pnexwpnas16_data03/70/3665770/html/wp-
includes/rest-api/class-wp-rest-server.php</b> on line <b>1244</b><br />

        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/json-2.0.3/lib
/json/common.rb:156:in `parse'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/json-2.0.3/lib
/json/common.rb:156:in `parse'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/httparty-0.14.
0/lib/httparty/parser.rb:118:in `json'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/httparty-0.14.
0/lib/httparty/parser.rb:138:in `parse_supported_format'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/httparty-0.14.
0/lib/httparty/parser.rb:105:in `parse'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/httparty-0.14.
0/lib/httparty/parser.rb:67:in `call'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/httparty-0.14.
0/lib/httparty/request.rb:345:in `parse_response'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/httparty-0.14.
0/lib/httparty/request.rb:297:in `block in handle_response'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/httparty-0.14.
0/lib/httparty/response.rb:25:in `call'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/httparty-0.14.
0/lib/httparty/response.rb:25:in `parsed_response'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/httparty-0.14.
0/lib/httparty/response.rb:80:in `method_missing'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/httparty-0.14.
0/lib/httparty/response.rb:48:in `inspect'
        from C:/RailsInstaller/Ruby2.2.0/bin/irb:11:in `<main>'
irb(main):012:0>

**Comment by claudiosanches** [comment]
Very easy to debug, since you need to fix the file `/home/content/p3pnexwpnas16_data03/70/3665770/html/wp-content/object-cache.php`

Not to mention that this file is not from WooCommerce or this REST API lib...

**Comment by ayalaalex** [comment]
Thanks Claudio.  Not sure how wordpress got messed up, anyhow I define WP_CACHE_KEY_SALT if it wasn't defined and that fixed the problem. weird.

**Comment by claudiosanches** [comment]
@ayalaalex this comes from your cache plugin, that suppose to define it for you.
