### ISSUE TITLE
require "woocommerce_api" gives error "cannot load such file -- woocommerce_api"

### ISSUE THREAD

**Issue by dhara-thacker** [woocommerce/wc-api-ruby#39]
I have installed the gem properly. And i'm  requiring the file in woocommerce_api in my code gives me this error

cannot load such file -- woocommerce_api

**Comment by Cdspada** [comment]
@dhara-thacker did you ever find a solution to this?

**Comment by dhara-thacker** [comment]
Hi, I don't quite remember what I did, but I just checked my code, and it seems I have commented out the require statement. So now, I'm using this API without actually requiring it.

Let me know if that helps.

Thanks,
Dhara

**Comment by Gil125** [comment]
I solved this just adding
`gem 'woocommerce_api'`
to my Gemfile and then using bundle install
